version: '3'
services:

  api:
    build: .
    command: npm start
    networks:
      - service_net
    ports:
      - '4000:4000'
    volumes:
      - ./src:/api/src
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '10m'

networks:
  service_net:
